/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class InputBarangView extends javax.swing.JFrame {

    /**
     * Creates new form Penginputan_Barang
     */
    public InputBarangView() {
        tabmodel = new DefaultTableModel(new Object[]{"ID Barang","Nama Barang","Jumlah","Harga"},0);
        initComponents();
        
    }

    public String getIDBarang_form() {
        return IDBarang_form.getText();
    }

    public String getHarga_form() {
        return harga_form.getText();
    }

    public String getJumlah_form() {
        return jumlah_form.getText();
    }

    public String getNamaBarang_form() {
        return namaBarang_form.getText();
    }

    public String getTanggalPesan_form() {
        return tanggalPesan_form.getText();
    }
    
    public String getCari_form(){
        return cari_form.getText();
    }
    
    public void tambahListener(ActionListener tambahListen){
        tambahBtn.addActionListener(tambahListen);
    }
    
    public void cariListener(ActionListener cariListen){
        cariBtn.addActionListener(cariListen);
    }
    
    public void cariFormListener(ActionListener cariFormListen){
        cari_form.addActionListener(cariFormListen);
    }
    
    public void Message(String s){
        JOptionPane.showMessageDialog(this, s);
    }
    
    public void updateTabel(ResultSet rs){

        tabmodel.setRowCount(0);
        
        try {
                rs.beforeFirst();
                while (rs.next())                
                {
                
                int count = tabmodel.getRowCount()+1;
                
                tabmodel.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});         
                }       
                rs.beforeFirst();
            
        } catch (Exception ex) {
            this.Message("Barang Tidak Ada");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tanggalPesan_form = new javax.swing.JTextField();
        namaBarang_form = new javax.swing.JTextField();
        jumlah_form = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        harga_form = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IDBarang_form = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cari_form = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        jLabel1.setText("Penginputan Barang");

        jLabel15.setText("Tanggal Pemesanan");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Jumlah Barang");

        tanggalPesan_form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tanggalPesan_formMouseEntered(evt);
            }
        });

        jLabel11.setText("Harga per Satuan");

        tambahBtn.setText("Tambah");

        jLabel3.setText("ID Barang");

        jLabel4.setText("cari barang");

        cariBtn.setText("cari");

        jTable2.setModel(tabmodel);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tanggalPesan_form, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(namaBarang_form)
                            .addComponent(jumlah_form)
                            .addComponent(tambahBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDBarang_form))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cari_form, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(harga_form, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tanggalPesan_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cari_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDBarang_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(namaBarang_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jumlah_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(harga_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(tambahBtn)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggalPesan_formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggalPesan_formMouseEntered
        // TODO add your handling code here:
        DateFormat dateform = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        tanggalPesan_form.setText(dateform.format(date));
    }//GEN-LAST:event_tanggalPesan_formMouseEntered

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        harga_form.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        IDBarang_form.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        namaBarang_form.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        
    }//GEN-LAST:event_jTable2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputBarangView().setVisible(true);
            }
        });
    }
    

    private DefaultTableModel tabmodel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDBarang_form;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cari_form;
    private javax.swing.JTextField harga_form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jumlah_form;
    private javax.swing.JTextField namaBarang_form;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JTextField tanggalPesan_form;
    // End of variables declaration//GEN-END:variables
}

