/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class PenjualanBarangView extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan_Barang
     */
    public PenjualanBarangView() {
        tabModelKeranjang = new DefaultTableModel(new Object[]{"ID Barang","Nama Barang","Jumlah","Harga","Total"},0);
        tabModelCari = new DefaultTableModel(new Object[]{"ID Barang","Nama Barang","Jumlah","Harga"},0);
        initComponents();
        
    }
    
    public void Row(){
        
    }
    
    public String getKodeForm(){
        return kodeBarangForm.getText();
    }
    
    public String getTotalForm(){
        return totalForm.getText();
    }

    public String getCariForm() {
        return cariForm.getText();
    }

    public int getHargaForm() {
        return Integer.parseInt(hargaForm.getText());
    }

    public int getJumlahForm() {
        return Integer.parseInt(jumlahForm.getText());
    }

    public String getKodeBarangForm() {
        return kodeBarangForm.getText();
    }

    public String getNamaBarangForm() {
        return namaBarangForm.getText();
    }
    
    public void setTotalForm(){
        int i = 0;
        int total = 0;
        while (i<tabModelKeranjang.getRowCount()){
            total = total + Integer.parseInt(tabModelKeranjang.getValueAt(i, 4).toString());
            System.out.println(total);
            i++;
        }
        totalForm.setText("Rp "+Integer.toString(total));
        
    }
    
    public void cariListener(ActionListener cariListen){
        cariBtn.addActionListener(cariListen);
    }
    
    public void tambahListener(ActionListener tambahListen){
        tambahBtn.addActionListener(tambahListen);
    }
    
    public void hapusListener(ActionListener hapusListen){
        hapusBtn.addActionListener(hapusListen);
    }
    
    public void batalListener(ActionListener batalListen){
        batalBtn.addActionListener(batalListen);
    }
    
    public void bayarListener(ActionListener bayarListen){
        bayarBtn.addActionListener(bayarListen);
    }
    
    public void updateCariTable(ResultSet rs){
        tabModelCari.setRowCount(0);
        
                try {
                rs.beforeFirst();
                while (rs.next())                
                {
                
                int count = tabModelCari.getRowCount()+1;
                
                tabModelCari.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});         
                }       
                rs.beforeFirst();
            
        } catch (Exception ex) {
            this.message("Barang Tidak Ada");
        }  
    }
    
    public void updateTableKeranjang(String id,String nama,int jumlah,int harga){
        int total = jumlah*harga;
        tabModelKeranjang.addRow(new Object[]{id,nama,jumlah,harga,total});
    }
    
    public void message(String s){
        JOptionPane.showMessageDialog(this, s);
    }
    
    public int nBarang(){
        return tabModelKeranjang.getRowCount();
    }
    
    public String[] kernajangRow(int i){
        System.out.println(tabModelKeranjang.getValueAt(i, 1).toString());
        System.out.println(tabModelKeranjang.getRowCount());
        String[] value = {tabModelKeranjang.getValueAt(i, 0).toString(),tabModelKeranjang.getValueAt(i, 1).toString(),tabModelKeranjang.getValueAt(i, 2).toString(),tabModelKeranjang.getValueAt(i, 3).toString(),tabModelKeranjang.getValueAt(i, 4).toString()};
        return value;
    }
    
    
    
    
    
    
    
    
    
    
    
    private DefaultTableModel tabModelKeranjang;
    private DefaultTableModel tabModelCari;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalForm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaBarangForm = new javax.swing.JTextField();
        hargaForm = new javax.swing.JTextField();
        kodeBarangForm = new javax.swing.JTextField();
        jumlahForm = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cariTable = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        cariForm = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        totalTable = new javax.swing.JTable();
        hapusBtn = new javax.swing.JButton();
        bayarBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        jLabel1.setText("Penjualan Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 0, -1, -1));

        totalForm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        totalForm.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalForm.setText("Rp.");
        getContentPane().add(totalForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 367, 171, 83));

        jLabel4.setText("Kode Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 69, -1, -1));

        jLabel5.setText("Nama Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 90, -1, -1));

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 117, -1, -1));

        jLabel7.setText("Jumlah");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 146, -1, -1));

        namaBarangForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangFormActionPerformed(evt);
            }
        });
        getContentPane().add(namaBarangForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 90, 70, -1));
        getContentPane().add(hargaForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 115, 70, -1));
        getContentPane().add(kodeBarangForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 65, 70, -1));
        getContentPane().add(jumlahForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 144, 70, -1));

        tambahBtn.setText("Tambah");
        getContentPane().add(tambahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 169, -1, -1));

        jLabel3.setText("Total Harga :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 398, 100, 23));

        cariTable.setModel(tabModelCari);
        cariTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cariTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(cariTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 65, 383, 119));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
        getContentPane().add(cariForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 40, 91, -1));

        cariBtn.setText("cari");
        getContentPane().add(cariBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 40, -1, 19));

        jLabel8.setText("cari barang");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 44, -1, -1));

        totalTable.setModel(tabModelKeranjang);
        jScrollPane3.setViewportView(totalTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 200, 657, 149));

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hapusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 397, -1, -1));

        bayarBtn.setText("Bayar");
        getContentPane().add(bayarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 395, -1, -1));

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(batalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 397, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariTableMousePressed
        // TODO add your handling code here:
        int row = cariTable.getSelectedRow();
        kodeBarangForm.setText(cariTable.getValueAt(row, 0).toString());
        namaBarangForm.setText(cariTable.getValueAt(row, 1).toString());
        hargaForm.setText(cariTable.getValueAt(row, 3).toString());
    }//GEN-LAST:event_cariTableMousePressed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        tabModelKeranjang.removeRow(totalTable.getSelectedRow());
        setTotalForm();
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        tabModelKeranjang.setRowCount(0);
        totalForm.setText("Rp.");
    }//GEN-LAST:event_batalBtnActionPerformed

    private void namaBarangFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanBarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanBarangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalBtn;
    private javax.swing.JButton bayarBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariForm;
    private javax.swing.JTable cariTable;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField hargaForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlahForm;
    private javax.swing.JTextField kodeBarangForm;
    private javax.swing.JTextField namaBarangForm;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JTextField totalForm;
    private javax.swing.JTable totalTable;
    // End of variables declaration//GEN-END:variables
}
